name: console-gmail-v3

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mails:
    uses: tech1-agency/tech1-ops/.github/workflows/actions-gmail-v3.yml@main
    secrets: inherit
    with:
      to: ${{ vars.EMAILS_TESTS }}
      previous_job_status: unknown
      html_body: |
        <b>Actor</b>: ${{ github.actor }}<br>
        <b>Trigger</b>: ${{ github.triggering_actor }}<br>
        <b>GitHub [json]</b>: ${{ toJson(github) }}<br>
