name: console-branch-docker-tag

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.setvars.outputs.docker_tag }}
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
            echo "docker_tag=dev" >> $GITHUB_OUTPUT
          fi

          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "docker_tag=prod" >> $GITHUB_OUTPUT
          fi

  mails:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Mails
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_GMAIL_USERNAME }}
          password: ${{ secrets.SMTP_GMAIL_PASSWORD }}
          subject: '${{ job.status }}: ${{ github.repository }} » ${{ github.ref_name }}, ${{ github.workflow }} # ${{ github.run_number }}'
          to: ${{ vars.EMAILS_TESTS }}
          from: ${{ vars.SMTP_GMAIL_FROM }}
          html_body: |
            <b>Status</b>: ${{ job.status }}<br>
            <b>CommitterId</b>: ${{ github.actor }}<br>
            <b>Actions</b>: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}<br>
            <b>Changes</b>: https://github.com/${{ github.repository }}/commit/${{ github.sha }}<br>
            <b>Committer</b>: ${{ github.event.commits[0].committer.name }}<br>
            <b>Message</b>: ${{ github.event.commits[0].message }}<br>
            <b>DockerTag</b>: ${{ needs.init.outputs.docker_tag }}<br>
